
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 29 09:48:49 CET 2023
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 8;
  public static final int INTEGER = 10;
  public static final int GREATER = 29;
  public static final int INT = 34;
  public static final int OUT = 13;
  public static final int MINUS = 27;
  public static final int SEMICOLON = 25;
  public static final int IS = 11;
  public static final int AND = 31;
  public static final int RECORD = 16;
  public static final int TYPE = 20;
  public static final int COMMA = 24;
  public static final int BEGIN = 2;
  public static final int PUT_LINE = 15;
  public static final int PAR_R = 23;
  public static final int LOOP = 12;
  public static final int IF = 9;
  public static final int ID = 36;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int PAR_L = 22;
  public static final int RETURN = 17;
  public static final int BY = 28;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int BECOMES = 32;
  public static final int CONSTANT = 4;
  public static final int COLON = 26;
  public static final int ELSE = 5;
  public static final int WHILE = 21;
  public static final int THEN = 18;
  public static final int END = 6;
  public static final int STRING = 35;
  public static final int FALSE = 7;
  public static final int PROCEDURE = 14;
  public static final int UNEQUAL = 30;
}

